// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow for recommending relevant products to users based on their search queries and browsing history.
 *
 * - recommendRelevantProducts - A function that takes a search query and browsing history as input and returns a list of recommended products.
 * - RecommendRelevantProductsInput - The input type for the recommendRelevantProducts function.
 * - RecommendRelevantProductsOutput - The return type for the recommendRelevantProducts function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendRelevantProductsInputSchema = z.object({
  query: z.string().describe('The user search query.'),
  browsingHistory: z.array(z.string()).describe('The user browsing history (list of product ids).'),
});
export type RecommendRelevantProductsInput = z.infer<typeof RecommendRelevantProductsInputSchema>;

const RecommendRelevantProductsOutputSchema = z.object({
  products: z.array(z.string()).describe('A list of recommended product ids.'),
});
export type RecommendRelevantProductsOutput = z.infer<typeof RecommendRelevantProductsOutputSchema>;

export async function recommendRelevantProducts(input: RecommendRelevantProductsInput): Promise<RecommendRelevantProductsOutput> {
  return recommendRelevantProductsFlow(input);
}

const trendingProductsTool = ai.defineTool({
  name: 'getTrendingProducts',
  description: 'Retrieves a list of trending product ids based on current market data.',
  inputSchema: z.object({
    count: z.number().describe('The number of trending products to retrieve.'),
  }),
  outputSchema: z.array(z.string()).describe('A list of trending product ids.'),
}, async (input) => {
  // TODO: Implement the actual logic to fetch trending products from a database or external API.
  // For now, return a hardcoded list.
  return ['trending-product-1', 'trending-product-2', 'trending-product-3'];
});

const prompt = ai.definePrompt({
  name: 'recommendRelevantProductsPrompt',
  input: {schema: RecommendRelevantProductsInputSchema},
  output: {schema: RecommendRelevantProductsOutputSchema},
  tools: [trendingProductsTool],
  system: `You are an expert in recommending products to users based on their search queries and browsing history. You should incorporate trending products into your recommendations to make them more relevant.

  Use the getTrendingProducts tool to fetch a list of trending product ids.

  Return a list of product ids that the user might be interested in.
  The result MUST be a JSON array of product ids.
  Consider current trends when making recommendations.`,
  prompt: `Based on the following search query: "{{query}}" and browsing history: "{{browsingHistory}}", recommend a list of product ids.`, // Ensure browsingHistory is properly formatted
});

const recommendRelevantProductsFlow = ai.defineFlow(
  {
    name: 'recommendRelevantProductsFlow',
    inputSchema: RecommendRelevantProductsInputSchema,
    outputSchema: RecommendRelevantProductsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
